# Generated by Django 5.1.2 on 2024-10-28 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your full name', max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Enter your email address for verification', max_length=254, verbose_name='Email Address')),
                ('phone_number', models.CharField(help_text='Enter your contact number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('visit_date', models.DateField(help_text='Select your preferred visit date', verbose_name='Visit Date')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Verification Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Visit Status')),
                ('notes', models.TextField(blank=True, help_text='Any additional information or special requests', null=True, verbose_name='Additional Notes')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'ordering': ['-created_at'],
            },
        ),
    ]
