# Generated by Django 5.1.3 on 2024-12-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_notification_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='phone',
        ),
    ]
