# Generated by Django 5.1.3 on 2024-12-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_remove_notification_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
