# Generated by Django 5.1.3 on 2024-12-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_remove_notification_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
