# Generated by Django 5.1.3 on 2024-12-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_notification_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='verification_token',
        ),
    ]
